#此工作流使用未经GitHub认证的操作。
#它们由第三方提供，并由
#单独的服务条款、隐私政策和支持
#documentation。
#
#zimperium-zscan GitHub操作扫描您的移动应用程序二进制文件(iOS或Android)
#和识别与安全性、隐私和合规性相关的漏洞。​
#
#先决条件：
#*需要有效的Zimperium zScan帐户。如果您不是现有的Zimperium帐户
#zScan客户，请访问https://www.zimperium.com/contact-us.
#*需要GitHub高级安全(GHAS)或公共存储库才能显示
#issue并查看GitHub代码扫描警报内的修正信息。
#
#了解更多信息和设置说明
#请访问：https://github.com/Zimperium/zScanMarketplace#自述

姓名:"Zimperium zScan"

在……之上:
推:
分支机构:[ "主要" ]
pull_request:
分支机构:[ "主要" ]

权限:
内容:读

工作:
zscan:
姓名:zScan
run-on:ubuntu-最新
权限:
内容:读用于操作/签出以获取代码的#
安全事件:写#for github/codeql-action/upload-sarif上传Sarif结果
行动:读#github/codeql-action/upload-sarif仅要求私有存储库获取Action运行状态
步骤:
-姓名:签出存储库
uses:操作/结帐@v4

-姓名:执行渐变生成
跑:./gradlew构建#更改此项以构建您的移动应用程序

-姓名:运行Zimperium zScan
uses:Zimperium/zscanmarketplace@bfc6670f6648d796098c251ccefcfdb98983174d
timeout-minutes:60
和……一起:
        #REPLACE:Zimperium客户端环境名称
client_env:env_string
        #REPLACE:Zimperium客户端ID
client_id:ID_string
        #REPLACE:Zimperium客户端机密
client_secret:${{secrets.ZSCAN_CLIENT_SECRET}}
        #REPLACE：.IPA或.apk的路径
app_file:app-release-unsigned.apk

-姓名:上传Sarif文件
uses:GitHub/codql-action/upload-sarif@v3
和……一起:
Sarif_file:Zimperium.sarif
